# Generated by Django 5.0 on 2023-12-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='id_produk',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
